INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (1, '9245476078', 'drpsatishchandra@yahoo.com ', 'APOLLO HOSPITAL, BANGALORE', 'DR P SATISH CHANDRA');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (2, null, 'chakkuthom@hotmail.com ', 'ST JOHN''S HOSPITAL, BANGALORE', 'DR THOMAS MATHEW');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (3, '9886775682', 'docnadig@rediffmail.com ', 'ST JOHN''S HOSPITAL, BANGALORE', 'DR RAGHUNANDAN NADIG');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (4, '9845371967', 'kamath_vikram@hotmail.com ', 'APOLLO HOSPITAL, BANGALORE', 'DR VIKRAM KAMATH');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (5, '9535212556', 'drknvraju08@gmail.com ', 'IGICH, BANGALORE', 'DR VYKUNTA RAJU');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (6, '9876208667', 'drnirajkumarsingh@gmail.com', 'AIIMS, RISHIKESH', 'DR NIRAJ KUMAR');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (7, '9341334340', 'drgunjankumar@gmail.com ', 'AIIMS, PATNA', 'DR GUNJAN KUMAR');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (8, '9431476689', 'drabhayranjan97@gmail.com', 'IGIMS, PATNA', 'DR ABHAY RANJAN');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (9, '9589709779', 'nirendra.neurology@aiimsbhopal.edu.in ', 'AIIMS, BHOPAL', 'DR NIRENDRA RAI');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (10, '9535079642', 'drsujit1@gmail.com ', 'APOLLO HOSPITAL, BANGALORE', 'DR SUJITH KUMAR');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (11, '9959035300', 'bvengamma@yahoo.com', 'SVIMS,TIRUPATHI', 'DR B VENGAMMA');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (12, '9538965945', 'dashdrgk@gmail.com ', 'NARAYANA HRUDYALAYA, BANGALORE', 'DR GOPAL KRISHNA DASH');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (13, '9174826942', 'saurav.grme@gmail.com', 'JIPMER, PUDUCHERRY', 'DR SOURABH SINGH RAJPUT');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (14, '9480542577', 'drvmgneurology@gmail.com ', 'SSIMS HOSPITAL, DAVANGERE', 'DR VEERANNA GADAD');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (15, '9036127274', 'ashokpathuri@outlook.com', 'JIPMER, PUDUCHERRY', 'DR PATHURI ASHOK');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (16, '9849007975', 'jaydipraychaudhuri@gmail.com ', 'YASHODHA HOSPITAL, SOMAJIGUDA', 'DR JAYDIP RAY C');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (17, '9400463055', 'drbidisha@yahoo.co.in', 'MANIPAL HOSPITAL, BANGALORE', 'DR BIDHISHA BANERJEE');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (18, '080-49695138', 'laboratory@sakraworldhospital.com ', 'SAKRA WORLD HOSPITAL, BANGALORE', 'DR SHIVAKUMAR');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (19, '9448076575', 'drjbagadi@gmail.com ', 'APOLLO HOSPITAL, BANGALORE', 'DR J B AGADI');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (20, '9606620844', 'drtanmayeethombare@gmail.com ', 'ST JOHN''S HOSPITAL, BANGALORE', 'DR TANMAYEE THROMBE');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (21, '9995525850', 'neurologycalicut@gmail.com ', 'GMC, CALICUT', 'DR JAMES JOSE');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (22, '9492806763', 'vyas.keeth@gmail.com', 'VYDEHI INSITITUTE', 'DR KEERTHI VYAS');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (23, '9427746889', 'mvdetroja@gmail.com', 'Sahaj Child Neurology & Epilepsy Centre', 'DR MAYANK V DETROJA');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (24, '9847018366', 'drhaq1971@yahoo.com', 'EMS Hospital', 'Dr Moyinul Haq');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (25, null, 'drsanthoo@yahoo.co.in', 'MANIPAL HOSPITAL, BANGALORE', 'Dr Santhosh NS');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (26, '9975880147', 'dnyaneshwarvj@gmail.com', 'KEM Hopsital, Mumbai', 'Dr Dnyaneshwar Jadhav');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (27, '9740332493', 'ramani.aruna84@gmail.com', 'Nero one Hospital, Trichy', 'Dr Aruna Ramani');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (28, '9447470049', 'cjsureshchandran@gmail.com', 'KIMS Hospital, Trivandrum', 'Dr Suresh Chandra');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (29, '9919787978', 'bhoisanjeev@gmail.com', 'AIIMS, Bhuvaneshwar', 'Dr S K Bhoi');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (30, '9901149066', 'abdulrawoof68bol@gmail.com ', 'NARAYANA HRUDYALAYA, BANGALORE', 'Dr Abdul Rawoof');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (31, '0831-2473777', 'drmaheshkamate@gmail.com', 'KLES PK Hospital', 'Dr Mahesh Kamate');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (32, '9686676403', 'neurology.kmc@manipal.edu', 'KMC, Manipal', 'Dr Aprana Rai');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (33, '9834703694', 'manishsalunkhe132@gmail.com', 'AIIMS, Delhi', 'Dr Manish Salunkhe');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (34, '9705027826', 'drchandrakanthtapsi@gmail.com', 'SKS Neuro Hospital', 'Dr Chandrakanth Tapsi');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (35, '6379708053', 'eprasanna2k1@gmail.com', 'MaNIPAL Hospital,Salem', 'Dr Prasanna Venkatesan');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (36, '7795797364', 'labvikram@gmail.com ', 'VIKRAM Hospital', 'Dr Swetha');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (37, '8589034566', 'info@firstneuro.in', 'First Neuro Hospital', 'Dr Shishir Duble');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (38, '7087008203', 'apcneuropediatrics@gmail.com', 'PGIMER, Chandigarh', 'Dr Naveen Sankhyan');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (39, '9437484678', 'biswamohan26@gmail.com', 'AIIMS, Delhi', 'Dr Biswamohan Mishra');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (40, '9686318158', 'manjusanehally@gmail.com ', 'MANIPAL HOSPITAL, Bangalore', 'Dr Manjunath M');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (41, '8708782023', 'sukriyasampathkumar@gmail.com', 'PGIMER, Chandigarh', 'Dr S Sukriya');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (42, '9448125792', 'drndatta@gmail.com', 'Brain & Neuro Clinic, Hubli', 'Dr Datta B Nadgir');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (43, '8437328757', 'sarathaleti@gmail.com', 'PGIMER, Chandigarh', 'Dr Sarath Aleti');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (44, null, 'moinaumir@yahoo.com', 'Apollo BGS hospital, Mysore', 'Dr Aumir Moin');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (45, '9447288221', 'drjacobgeorge35@gmail.com', 'GMC, Kottayam', 'Dr Jacob George');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (46, '9400402408', 'drdarlymammen@gmail.com', 'ICH, Kottayam', 'Dr Darly Mammen');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (47, null, 'drvikramhuded@gmail.com', 'NARAYANA HRUDYALAYA, BANGALORE', 'Dr Vikram Huded');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (48, '080-71222168', 'kuldeepshettyneuro@gmail.com', 'NH, Hospital', 'Dr Kuldeep Shetty');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (49, '9972642211', 'drbineesh1980@gmail.com', 'Moulana Hospital', 'Dr Bineesh C');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (50, null, 'rohitbhatia71@yahoo.com', 'AIIMS, New delhi', 'Dr Rohit Bhatia');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (51, '8193829825', 'ankitmbd2010@gmail.com', 'COSMOS Hospital', 'Dr Ankit Singhal');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (52, '0427-2319395', 'baluneuro@yahoo.co.in', 'SIMS Chelum Hospital, Salem', 'Dr N Balamurgan');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (53, '9544146005', 'drshibabudheenp@gmail.com', 'IQRAA Hospital, Calicut', 'Dr Shibabudheen P');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (54, '9766009294', 'smrutirb11@gmail.com', 'AIIMS, New delhi', 'Dr Smruti');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (55, '8075357660', 'baijuputhanveetil@gmail.com', 'Sree Gokulam Medical  College', 'Dr Baiju Puthan');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (56, '7575919195', 'singhdeependra11@yahoo.com', 'Nehru Hospital, PGIMER, Chandigarh', 'Dr Deependra Singh');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (57, '9964739910', 'jskaushik2010@gmail.com', 'PGIMS, Rothak', 'Dr J S Kaushik');
INSERT INTO neuroLab.doctor (id, contact_no, email_id, hospital_name, name) VALUES (58, '9718980551', 'luvbansal30@gmail.com', 'GB pant hospital, New Delhi', 'Dr Luv Bansal');